apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-config
  namespace: chat
data:
  SPRING_PROFILES_ACTIVE: "prod"
  APP_FRONTEND_URL: "http://172.28.4.215:3000"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "http://172.28.4.215:9092"

  # Redis 호스트/포트가 코드에서 기본 localhost를 쓴다면 함께 넣으세요.
  SPRING_DATA_REDIS_HOST: "http://172.28.4.215"
  SPRING_DATA_REDIS_PORT: "6379"