apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: couu/chatservice-kotlin:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9090

          envFrom:
            - configMapRef:
                name: chat-config
            - secretRef:
                name: chat-secret

          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            # Pod마다 고유 consumer group/id 부여
            - name: CHAT_KAFKA_CONSUMER_GROUP_ID
              value: "chat-ws-$(POD_NAME)"
            - name: CHAT_KAFKA_DM_CONSUMER_GROUP_ID
              value: "dm-ws-$(POD_NAME)"
            - name: APP_INSTANCE_ID
              value: "$(POD_NAME)"

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9090
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9090
            initialDelaySeconds: 40
            periodSeconds: 20

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"